### ISSUE TITLE
What fore are these suggests ?

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/openmandriva-repos#1]
Hi, do you know what for are all those suggests ? We are not using ibus or phonon-vlc, neither gcc by default.

https://github.com/OpenMandrivaAssociation/openmandriva-repos/blob/4896a5c3cc4862cae3ae4760ddba10cbb8567963/openmandriva-repos.spec#L133

**Comment by Conan-Kudo** [comment]
@tpgxyz 

All the Suggests are wrong. They need to be adjusted to match OpenMandriva's actual preferences. Currently, the Suggests are from the earlier snapshot of mageia-repos that this package is based on, which its list is based on the prefer.vendor.list file shipped in Mageia's meta-task package.

This needs to be resynchronized with the prefer.vendor.list for OpenMandriva.

**Comment by tpgxyz** [comment]
@Conan-Kudo  Thanks for the explanation. Fixed
